[platformio]
; Menentukan direktori source kode berada di folder root (bersama dengan file .ino)
; Ini mempertahankan kompatibilitas dengan Arduino IDE
src_dir = .
include_dir = .

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Kecepatan baud rate Serial Monitor sesuai dengan yang ada di kodingan
monitor_speed = 9600

; Dependensi library yang digunakan oleh project ini
lib_deps =
  adafruit/RTClib
  dfrobot/DFRobotDFPlayerMini
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library
  plerup/EspSoftwareSerial

; [PENTING] Jika board ESP32-S3 Anda menggunakan Port USB Native langsung (tanpa chip TTL seperti CP2102),
; Anda perlu menghapus tanda titik koma (;) pada dua baris build_flags di bawah agar Serial Monitor/Upload berfungsi:
; build_flags = 
;   -D ARDUINO_USB_MODE=1
;   -D ARDUINO_USB_CDC_ON_BOOT=1
