[platformio]
; Menentukan direktori source kode berada di folder root (bersama dengan file .ino)
; Ini mempertahankan kompatibilitas dengan Arduino IDE
src_dir = .
include_dir = .

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Kecepatan baud rate Serial Monitor sesuai dengan yang ada di kodingan
monitor_speed = 9600 

; Upload options
upload_speed = 921600

; Dependensi library yang digunakan oleh project ini
lib_deps =
   adafruit/RTClib
   dfrobot/DFRobotDFPlayerMini
   adafruit/Adafruit GFX Library
   adafruit/Adafruit ST7735 and ST7789 Library
   plerup/EspSoftwareSerial
   bblanchon/ArduinoJson

; LittleFS filesystem & partition scheme
board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv  ; Perbesar ruang app + LittleFS

; Build flags
build_flags =
   -DCORE_DEBUG_LEVEL=0
;   -DARDUINO_USB_MODE=1
;   -DARDUINO_USB_CDC_ON_BOOT=1
